export const StorageNBATeams = {
  NBATeamsFullName: [
      "Atlanta Hawks",
      "Boston Celtics",
      "Brooklyn Nets",
      "Charlotte Hornets",
      "Chicago Bulls",
      "Cleveland Cavaliers",
      "Dallas Mavericks",
      "Denver Nuggets",
      "Detroit Pistons",
      "Golden State Warriors",
      "Houston Rockets",
      "Indiana Pacers",
      "Los Angeles Clippers",
      "Los Angeles Lakers",
      "Memphis Grizzlies",
      "Miami Heat",
      "Milwaukee Bucks",
      "Minnesota Timberwolves",
      "New Orleans Pelicans",
      "New York",
      "Oklahoma City Thunder",
      "Orlando Magic",
      "Philadelphia 76ers",
      "Phoenix Suns",
      "Portland Trail Blazers",
      "Sacramento Kings",
      "San Antonio Spurs",
      "Toronto Raptors",
      "Utah Jazz",
      "Washington Wizards"
  ],
  NBATeams: [
      "Atlanta",
      "Boston",
      "Brooklyn",
      "Charlotte",
      "Chicago",
      "Cleveland",
      "Dallas",
      "Denver",
      "Detroit",
      "Golden State",
      "Houston",
      "Indiana",
      "LA",
      "Los Angeles",
      "Memphis",
      "Miami",
      "Milwaukee",
      "Minnesota",
      "New Orleans",
      "New York",
      "Oklahoma City",
      "Orlando",
      "Philadelphia",
      "Phoenix",
      "Portland",
      "Sacramento",
      "San Antonio",
      "Toronto",
      "Utah",
      "Washington"
  ],
  NBATeamsNickNames: {
      Atlanta: "Hawks",
      Boston: "Celtics",
      Brooklyn: "Nets",
      Charlotte: "Hornets",
      Chicago: "Bulls",
      Cleveland: "Cavaliers",
      Dallas: "Mavericks",
      Denver: "Nuggets",
      Detroit: "Pistons",
      GoldenState: "Warriors",
      Houston: "Rockets",
      Indiana: "Pacers",
      LA: "Clippers",
      LosAngeles: "Lakers",
      Memphis: "Grizzlies",
      Miami: "Heat",
      Milwaukee: "Bucks",
      Minnesota: "Timberwolves",
      NewOrleans: "Pelicans",
      NewYork: "Knicks",
      OklahomaCity: "Thunder",
      Orlando: "Magic",
      Philadelphia: "76ers",
      Phoenix: "Suns",
      Portland: "Trailblazers",
      Sacramento: "Kings",
      SanAntonio: "Spurs",
      Toronto: "Raptors",
      Utah: "Jazz",
      Washington: "Wizards"
  },
  predictorTeamIDs: {
      Hawks: "1",
      Celtics: "2",
      Nets: "3",
      Hornets: "4",
      Bulls: "5",
      Cavaliers: "6",
      Pistons: "7",
      Pacers: "8",
      Heat: "9",
      Bucks: "10",
      Knicks: "11",
      Magic: "12",
      '76ers': "13",
      Raptors: "14",
      Wizards: "15",
      Mavericks: "16",
      Nuggets: "17",
      arriors: "18",
      Rockets: "19",
      Clippers: "20",
      Lakers: "21",
      Grizzlies: "22",
      Timberwolves: "23",
      Pelicans: "24",
      Thunder: "25",
      Suns: "26",
      Trailblazers: "27",
      Kings: "28",
      Spurs: "29",
      Jazz: "30"
  }
};

// var object2 = {
//   Hawks: "1",
//   Celtics: "2",
//   Nets: "3",
//   Hornets: "4",
//   Bulls: "5",
//   Cavaliers: "6",
//   Pistons: "7",
//   Pacers: "8",
//   Heat: "9",
//   Bucks: "10",
//   Knicks: "11",
//   Magic: "12",
//   '76ers': "13",
//   Raptors: "14",
//   Wizards: "15",
//   Mavericks: "16",
//   Nuggets: "17",
//   arriors: "18",
//   Rockets: "19",
//   Clippers: "20",
//   Lakers: "21",
//   Grizzlies: "22",
//   Timberwolves: "23",
//   Pelicans: "24",
//   Thunder: "25",
//   Suns: "26",
//   Trailblazers: "27",
//   Kings: "28",
//   Spurs: "29",
//   Jazz: "30"
// };

// var object3 = {
//   Hawks: "1",
//   Celtics: "2",
//   Nets: "3",
//   Hornets: "4",
//   Bulls: "5",
//   Cavaliers: "6",
//   Pistons: "7",
//   Pacers: "8",
//   Heat: "9",
//   Bucks: "10",
//   Knicks: "11",
//   Magic: "12",
//   6ers: "13",
//   Raptors: "14",
//   Wizards: "15",
//   Mavericks: "16",
//   Nuggets: "17",
//   arriors: "18",
//   Rockets: "19",
//   Clippers: "20",
//   Lakers: "21",
//   Grizzlies: "22",
//   Timberwolves: "23",
//   Pelicans: "24",
//   Thunder: "25",
//   Suns: "26",
//   Trailblazers: "27",
//   Kings: "28",
//   Spurs: "29",
//   Jazz: "30"
// };